---
- hosts: yumservers
  gather_facts: False

  tasks:
    - name: yum update
      raw: yum update -y
    - name: Install Python
      raw: test -e /usr/bin/python || (yum install -y python libselinux-python)

    - name: Create /root/.ssh
      file: path=/root/.ssh state=directory mode=0700

    - name: Create /root/.ssh/authorized_keys
      file: path=/root/.ssh/authorized_keys state=touch mode=0700

    - name: Add key to authorized_keys
      lineinfile: dest=/root/.ssh/authorized_keys line="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
